import type { AchievementIconId } from "@/assets/achievements/achievement-icons";
import type { AchievementRarity } from "@/components/achievements/AchievementBadge";

export type AchievementCategory =
  | "getting_started"
  | "mission_control"
  | "journal"
  | "routes"
  | "backtesting"
  | "industry"
  | "classified";

export interface AchievementDefinition {
  id: AchievementIconId;
  title: string;
  description: string;
  category: AchievementCategory;
  rarity: AchievementRarity;
  points: number;
  iconId: AchievementIconId;
  hidden: boolean;
  progressMax: number;
}

export const achievementCategories: Array<{ id: AchievementCategory; label: string }> = [
  { id: "getting_started", label: "Getting Started" },
  { id: "mission_control", label: "Mission Control" },
  { id: "journal", label: "Journal & Reality Check" },
  { id: "routes", label: "Routes & Hauling" },
  { id: "backtesting", label: "Backtesting" },
  { id: "industry", label: "Industry" },
  { id: "classified", label: "Classified" },
];

export const achievementDefinitions: AchievementDefinition[] = [
  {
    id: "first-contact",
    title: "First Contact",
    description: "Complete your first market scan.",
    category: "getting_started",
    rarity: "bronze",
    points: 10,
    iconId: "first-contact",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "market-analyst",
    title: "Market Analyst",
    description: "Scan 100 market rows across any scanner.",
    category: "getting_started",
    rarity: "silver",
    points: 25,
    iconId: "market-analyst",
    hidden: false,
    progressMax: 100,
  },
  {
    id: "deep-scanner",
    title: "Deep Scanner",
    description: "Scan 1,000 market rows.",
    category: "getting_started",
    rarity: "gold",
    points: 60,
    iconId: "deep-scanner",
    hidden: false,
    progressMax: 1000,
  },
  {
    id: "ledger-opened",
    title: "Ledger Opened",
    description: "Open the wallet and cashflow ledger.",
    category: "getting_started",
    rarity: "platinum",
    points: 10,
    iconId: "ledger-opened",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "portfolio-view",
    title: "Portfolio View",
    description: "Open character portfolio analysis.",
    category: "getting_started",
    rarity: "classified",
    points: 10,
    iconId: "portfolio-view",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "risk-aware",
    title: "Risk Aware",
    description: "Open the risk tab or inspect route danger.",
    category: "getting_started",
    rarity: "bronze",
    points: 15,
    iconId: "risk-aware",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "comeback-trader",
    title: "Comeback Trader",
    description: "Reconcile a profitable trade after a previous losing one.",
    category: "getting_started",
    rarity: "silver",
    points: 30,
    iconId: "comeback-trader",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "first-mission",
    title: "First Mission",
    description: "Create your first journal trade from Mission Control.",
    category: "mission_control",
    rarity: "gold",
    points: 15,
    iconId: "first-mission",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "mission-controller",
    title: "Mission Controller",
    description: "Open Mission Control 10 times.",
    category: "mission_control",
    rarity: "platinum",
    points: 50,
    iconId: "mission-controller",
    hidden: false,
    progressMax: 10,
  },
  {
    id: "not-so-fast",
    title: "Not So Fast",
    description: "Let Mission Control reduce a trade quantity due to real limits.",
    category: "mission_control",
    rarity: "classified",
    points: 35,
    iconId: "not-so-fast",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "depth-matters",
    title: "Depth Matters",
    description: "Inspect a plan where VWAP depth changes the top-of-book result.",
    category: "mission_control",
    rarity: "bronze",
    points: 30,
    iconId: "depth-matters",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "no-paper-profit",
    title: "No Paper Profit",
    description: "Catch a plan with negative worst-case PnL.",
    category: "mission_control",
    rarity: "silver",
    points: 80,
    iconId: "no-paper-profit",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "capital-guard",
    title: "Capital Guard",
    description: "Have wallet reserve limit the executable quantity.",
    category: "mission_control",
    rarity: "gold",
    points: 45,
    iconId: "capital-guard",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "exposure-control",
    title: "Exposure Control",
    description: "Have item exposure limit a plan.",
    category: "mission_control",
    rarity: "platinum",
    points: 40,
    iconId: "exposure-control",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "fee-awareness",
    title: "Fee Awareness",
    description: "Review fees inside Mission Control.",
    category: "mission_control",
    rarity: "classified",
    points: 15,
    iconId: "fee-awareness",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "too-small-to-trade",
    title: "Too Small To Trade",
    description: "Let Mission Control flag an opportunity as too small.",
    category: "mission_control",
    rarity: "bronze",
    points: 20,
    iconId: "too-small-to-trade",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "big-ticket",
    title: "Big Ticket",
    description: "Plan a trade that freezes at least 1B ISK.",
    category: "mission_control",
    rarity: "silver",
    points: 100,
    iconId: "big-ticket",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "planned-operator",
    title: "Planned Operator",
    description: "Create 5 planned journal trades.",
    category: "journal",
    rarity: "gold",
    points: 25,
    iconId: "planned-operator",
    hidden: false,
    progressMax: 5,
  },
  {
    id: "execution-discipline",
    title: "Execution Discipline",
    description: "Create 25 planned journal trades.",
    category: "journal",
    rarity: "platinum",
    points: 50,
    iconId: "execution-discipline",
    hidden: false,
    progressMax: 25,
  },
  {
    id: "closed-loop",
    title: "Closed Loop",
    description: "Reconcile your first planned trade against live data.",
    category: "journal",
    rarity: "classified",
    points: 60,
    iconId: "closed-loop",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "reality-check",
    title: "Reality Check",
    description: "Compare expected PnL against actual PnL.",
    category: "journal",
    rarity: "bronze",
    points: 45,
    iconId: "reality-check",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "green-ledger",
    title: "Green Ledger",
    description: "Reconcile a profitable trade.",
    category: "journal",
    rarity: "silver",
    points: 25,
    iconId: "green-ledger",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "red-lesson",
    title: "Red Lesson",
    description: "Reconcile a losing trade and keep the lesson in the journal.",
    category: "journal",
    rarity: "gold",
    points: 25,
    iconId: "red-lesson",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "clean-exit",
    title: "Clean Exit",
    description: "Reconcile a trade that beats the plan.",
    category: "journal",
    rarity: "platinum",
    points: 80,
    iconId: "clean-exit",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "slippage-student",
    title: "Slippage Student",
    description: "Find slippage as a real loss reason.",
    category: "journal",
    rarity: "classified",
    points: 35,
    iconId: "slippage-student",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "market-moved",
    title: "Market Moved",
    description: "Reconcile a trade where price movement hurt the plan.",
    category: "journal",
    rarity: "bronze",
    points: 35,
    iconId: "market-moved",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "undercut-tax",
    title: "Undercut Tax",
    description: "Record undercut or relist pressure as a trade cost.",
    category: "journal",
    rarity: "silver",
    points: 35,
    iconId: "undercut-tax",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "route-planner",
    title: "Route Planner",
    description: "Check a hauling route or route execution plan.",
    category: "routes",
    rarity: "gold",
    points: 15,
    iconId: "route-planner",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "cargo-math",
    title: "Cargo Math",
    description: "Open a route plan where cargo fit changes execution.",
    category: "routes",
    rarity: "platinum",
    points: 40,
    iconId: "cargo-math",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "safe-route",
    title: "Safe Route",
    description: "Choose or inspect the safest route mode.",
    category: "routes",
    rarity: "classified",
    points: 20,
    iconId: "safe-route",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "isk-hour-mindset",
    title: "ISK/hour Mindset",
    description: "Inspect the max ISK/hour route mode.",
    category: "routes",
    rarity: "bronze",
    points: 50,
    iconId: "isk-hour-mindset",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "camp-check",
    title: "Camp Check",
    description: "Inspect gank or camper risk on a route.",
    category: "routes",
    rarity: "silver",
    points: 40,
    iconId: "camp-check",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "dotlan-navigator",
    title: "DOTLAN Navigator",
    description: "Open route context in DOTLAN when support is available.",
    category: "routes",
    rarity: "gold",
    points: 15,
    iconId: "dotlan-navigator",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "backtest-curious",
    title: "Backtest Curious",
    description: "Run your first Paper Backtest.",
    category: "backtesting",
    rarity: "platinum",
    points: 25,
    iconId: "backtest-curious",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "backtest-grinder",
    title: "Backtest Grinder",
    description: "Run 10 Paper Backtests.",
    category: "backtesting",
    rarity: "classified",
    points: 60,
    iconId: "backtest-grinder",
    hidden: false,
    progressMax: 10,
  },
  {
    id: "snapshot-believer",
    title: "Snapshot Believer",
    description: "Run a backtest that uses recorded orderbook snapshot coverage.",
    category: "backtesting",
    rarity: "bronze",
    points: 50,
    iconId: "snapshot-believer",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "paper-millionaire",
    title: "Paper Millionaire",
    description: "Run a backtest whose diagnostics reduce paper profit with real constraints.",
    category: "backtesting",
    rarity: "silver",
    points: 80,
    iconId: "paper-millionaire",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "industry-check",
    title: "Industry Check",
    description: "Run your first industry analysis.",
    category: "industry",
    rarity: "gold",
    points: 20,
    iconId: "industry-check",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "blueprint-mindset",
    title: "Blueprint Mindset",
    description: "Inspect blueprint coverage for an industry plan.",
    category: "industry",
    rarity: "platinum",
    points: 40,
    iconId: "blueprint-mindset",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "material-realist",
    title: "Material Realist",
    description: "Run a depth-aware material cost check.",
    category: "industry",
    rarity: "classified",
    points: 50,
    iconId: "material-realist",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "job-planner",
    title: "Job Planner",
    description: "Create or update an industry job plan.",
    category: "industry",
    rarity: "bronze",
    points: 45,
    iconId: "job-planner",
    hidden: false,
    progressMax: 1,
  },
  {
    id: "almost-trapped",
    title: "Almost Trapped",
    description: "Classified until unlocked.",
    category: "classified",
    rarity: "silver",
    points: 150,
    iconId: "almost-trapped",
    hidden: true,
    progressMax: 1,
  },
  {
    id: "classified-unknown-01",
    title: "Too Good To Be True",
    description: "Classified until unlocked.",
    category: "classified",
    rarity: "gold",
    points: 150,
    iconId: "classified-unknown-01",
    hidden: true,
    progressMax: 1,
  },
  {
    id: "classified-unknown-02",
    title: "Diamond Hands Wrong Game",
    description: "Classified until unlocked.",
    category: "classified",
    rarity: "platinum",
    points: 150,
    iconId: "classified-unknown-02",
    hidden: true,
    progressMax: 1,
  },
  {
    id: "discipline-over-greed",
    title: "Discipline Over Greed",
    description: "Classified until unlocked.",
    category: "classified",
    rarity: "classified",
    points: 120,
    iconId: "discipline-over-greed",
    hidden: true,
    progressMax: 1,
  },
  {
    id: "classified-unknown-03",
    title: "Quiet Professional",
    description: "Classified until unlocked.",
    category: "classified",
    rarity: "bronze",
    points: 150,
    iconId: "classified-unknown-03",
    hidden: true,
    progressMax: 1,
  },
  {
    id: "classified-unknown-04",
    title: "The Auditor",
    description: "Classified until unlocked.",
    category: "classified",
    rarity: "silver",
    points: 150,
    iconId: "classified-unknown-04",
    hidden: true,
    progressMax: 1,
  },
];

export const achievementDefinitionById = Object.fromEntries(
  achievementDefinitions.map((definition) => [definition.id, definition]),
) as Record<AchievementIconId, AchievementDefinition>;
