package api

import (
	"database/sql"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"strconv"
	"strings"
	"time"

	"eve-flipper/internal/db"
)

// Order-book archiving is off until switched on, so an install that never
// opens the Backtest tab never pays for it. When it is on, these bound how
// much it can accumulate.
const (
	// orderBookRetentionDays is how long archived snapshots are kept. A week
	// is enough span for replay to say something while keeping the table in
	// the hundreds of megabytes; the archive is regenerated by ordinary
	// scanning, so aging it out costs nothing that cannot be re-collected.
	// The sweep only runs while recording is on, so switching archiving off
	// freezes what you already have instead of quietly aging it out.
	orderBookRetentionDays = 7
	// orderBookSweepInterval is how often the retention sweep runs. The first
	// pass is delayed so it never competes with startup.
	orderBookSweepInterval = 6 * time.Hour
	orderBookSweepDelay    = 5 * time.Minute
)

// applyOrderBookRecording pushes the persisted archiving switch onto the ESI
// client. Called at startup and whenever the switch is flipped.
func (s *Server) applyOrderBookRecording() bool {
	enabled := s.db != nil && s.db.OrderBookRecordingEnabled()
	if s.esi != nil {
		s.esi.SetMarketOrderRecordingEnabled(enabled)
	}
	return enabled
}

// startOrderBookRetention ages out archived snapshots in the background.
// Without it the archive only shrinks when someone remembers to press the
// cleanup button in the Backtest tab, and a region-wide book is ~400k rows.
func (s *Server) startOrderBookRetention() {
	if s.db == nil {
		return
	}
	go func() {
		time.Sleep(orderBookSweepDelay)
		for {
			// Deliberately a no-op while archiving is off: an archive you
			// stopped adding to is one you chose to keep, not one to expire.
			if s.esi == nil || s.esi.MarketOrderRecordingEnabled() {
				plan, err := s.db.CleanupOrderBookSnapshots(orderBookRetentionDays, false, false)
				switch {
				case err != nil:
					log.Printf("[Orderbook] retention sweep failed: %v", err)
				case plan.SnapshotsDeleted > 0:
					log.Printf("[Orderbook] retention sweep removed %d snapshots / %d levels older than %s",
						plan.SnapshotsDeleted, plan.LevelsDeleted, plan.Cutoff)
				}
			}
			time.Sleep(orderBookSweepInterval)
		}
	}()
}

func (s *Server) handleOrderBookRecording(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodGet {
		writeJSON(w, s.orderBookRecordingState())
		return
	}

	var req struct {
		Enabled bool `json:"enabled"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	if s.db == nil {
		writeError(w, http.StatusServiceUnavailable, "database unavailable")
		return
	}
	if err := s.db.SetOrderBookRecordingEnabled(req.Enabled); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to save orderbook recording setting")
		return
	}
	enabled := s.applyOrderBookRecording()
	log.Printf("[Orderbook] recording set to %v", enabled)
	writeJSON(w, s.orderBookRecordingState())
}

// orderBookRecordingState describes archiving to the UI. tracked_type_count is
// the honest answer to "what will this actually store": zero means the archive
// is on but has nothing it considers worth keeping yet, which the panel needs
// to say out loud rather than showing an enabled switch that writes nothing.
func (s *Server) orderBookRecordingState() map[string]interface{} {
	tracked := 0
	if s.db != nil {
		tracked = len(s.db.OrderBookInterestTypes())
	}
	return map[string]interface{}{
		"enabled":            s.esi != nil && s.esi.MarketOrderRecordingEnabled(),
		"retention_days":     orderBookRetentionDays,
		"tracked_type_count": tracked,
	}
}

func parseOptionalInt32Query(r *http.Request, key string) (int32, bool, error) {
	raw := strings.TrimSpace(r.URL.Query().Get(key))
	if raw == "" {
		return 0, false, nil
	}
	v, err := strconv.ParseInt(raw, 10, 32)
	if err != nil || v < 0 {
		return 0, false, err
	}
	return int32(v), true, nil
}

func parseOptionalInt64Query(r *http.Request, key string) (int64, bool, error) {
	raw := strings.TrimSpace(r.URL.Query().Get(key))
	if raw == "" {
		return 0, false, nil
	}
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil || v < 0 {
		return 0, false, err
	}
	return v, true, nil
}

func parseOptionalLimitQuery(r *http.Request, defaultLimit, maxLimit int) (int, error) {
	raw := strings.TrimSpace(r.URL.Query().Get("limit"))
	if raw == "" {
		return defaultLimit, nil
	}
	v, err := strconv.Atoi(raw)
	if err != nil || v <= 0 {
		return 0, err
	}
	if v > maxLimit {
		v = maxLimit
	}
	return v, nil
}

func (s *Server) handleOrderBookSnapshots(w http.ResponseWriter, r *http.Request) {
	if s.db == nil {
		writeJSON(w, map[string]interface{}{
			"snapshots": []db.OrderBookSnapshotMeta{},
			"count":     0,
		})
		return
	}

	regionID, _, err := parseOptionalInt32Query(r, "region_id")
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid region_id")
		return
	}
	typeID, _, err := parseOptionalInt32Query(r, "type_id")
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid type_id")
		return
	}
	locationID, _, err := parseOptionalInt64Query(r, "location_id")
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid location_id")
		return
	}
	limit, err := parseOptionalLimitQuery(r, 100, 1000)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid limit")
		return
	}

	snapshots, err := s.db.ListOrderBookSnapshots(db.OrderBookSnapshotFilter{
		Source:     r.URL.Query().Get("source"),
		RegionID:   regionID,
		OrderType:  r.URL.Query().Get("order_type"),
		TypeID:     typeID,
		LocationID: locationID,
		Limit:      limit,
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to list orderbook snapshots")
		return
	}
	if snapshots == nil {
		snapshots = []db.OrderBookSnapshotMeta{}
	}
	writeJSON(w, map[string]interface{}{
		"snapshots": snapshots,
		"count":     len(snapshots),
	})
}

func (s *Server) handleOrderBookLevels(w http.ResponseWriter, r *http.Request) {
	if s.db == nil {
		writeJSON(w, map[string]interface{}{
			"snapshot": nil,
			"levels":   []db.OrderBookLevel{},
			"count":    0,
		})
		return
	}
	snapshotID, err := strconv.ParseInt(strings.TrimSpace(r.PathValue("snapshotID")), 10, 64)
	if err != nil || snapshotID <= 0 {
		writeError(w, http.StatusBadRequest, "invalid snapshot id")
		return
	}

	typeID, _, err := parseOptionalInt32Query(r, "type_id")
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid type_id")
		return
	}
	locationID, _, err := parseOptionalInt64Query(r, "location_id")
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid location_id")
		return
	}
	limit, err := parseOptionalLimitQuery(r, 5000, 50000)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid limit")
		return
	}

	snapshot, err := s.db.GetOrderBookSnapshot(snapshotID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			writeError(w, http.StatusNotFound, "orderbook snapshot not found")
			return
		}
		writeError(w, http.StatusInternalServerError, "failed to load orderbook snapshot")
		return
	}
	levels, err := s.db.GetOrderBookLevels(snapshotID, db.OrderBookLevelFilter{
		TypeID:     typeID,
		LocationID: locationID,
		Side:       r.URL.Query().Get("side"),
		Limit:      limit,
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to load orderbook levels")
		return
	}
	if levels == nil {
		levels = []db.OrderBookLevel{}
	}
	writeJSON(w, map[string]interface{}{
		"snapshot": snapshot,
		"levels":   levels,
		"count":    len(levels),
	})
}

func (s *Server) handleOrderBookStats(w http.ResponseWriter, r *http.Request) {
	limit, err := parseOptionalLimitQuery(r, 10, 50)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid limit")
		return
	}
	if s.db == nil {
		writeJSON(w, db.OrderBookStats{
			TopTypes:     []db.OrderBookStatsType{},
			TopLocations: []db.OrderBookStatsLocation{},
		})
		return
	}
	stats, err := s.db.GetOrderBookStats(limit)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to load orderbook stats")
		return
	}
	if stats.TopTypes == nil {
		stats.TopTypes = []db.OrderBookStatsType{}
	}
	if stats.TopLocations == nil {
		stats.TopLocations = []db.OrderBookStatsLocation{}
	}
	writeJSON(w, stats)
}

type orderBookCleanupRequest struct {
	KeepDays      int  `json:"keep_days"`
	DryRun        bool `json:"dry_run"`
	Vacuum        bool `json:"vacuum"`
	BatchSize     int  `json:"batch_size"`
	MaxSeconds    int  `json:"max_seconds"`
	MaxSnapshots  int  `json:"max_snapshots"`   // legacy alias for batch_size
	MaxDurationMs int  `json:"max_duration_ms"` // optional precise time budget
}

func (s *Server) handleOrderBookCleanup(w http.ResponseWriter, r *http.Request) {
	if s.rejectHostedMaintenance(w, "orderbook cleanup") {
		return
	}
	if s.db == nil {
		writeError(w, http.StatusServiceUnavailable, "orderbook database not ready")
		return
	}
	var req orderBookCleanupRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid json")
		return
	}
	if req.KeepDays <= 0 {
		writeError(w, http.StatusBadRequest, "keep_days must be positive")
		return
	}
	batchSize := req.BatchSize
	if batchSize <= 0 {
		batchSize = req.MaxSnapshots
	}
	if batchSize <= 0 {
		batchSize = db.DefaultOrderBookCleanupBatchSnapshots
	}
	maxDuration := time.Duration(req.MaxSeconds) * time.Second
	if req.MaxDurationMs > 0 {
		maxDuration = time.Duration(req.MaxDurationMs) * time.Millisecond
	}
	if maxDuration <= 0 {
		maxDuration = time.Duration(db.DefaultOrderBookCleanupMaxSeconds) * time.Second
	}

	var plan db.OrderBookCleanupPlan
	var err error
	if req.DryRun {
		plan, err = s.db.CleanupOrderBookSnapshots(req.KeepDays, true, false)
	} else {
		plan, err = s.db.CleanupOrderBookSnapshotsBatches(req.KeepDays, batchSize, maxDuration)
		plan.DryRun = false
		plan.Vacuum = req.Vacuum
		if err == nil && req.Vacuum && plan.SnapshotsDeleted > 0 {
			err = s.db.Vacuum()
		}
	}
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	writeJSON(w, plan)
}
